;;; shinmunji-theme.el --- Like an old newspaper

;; Copyright (C) 2018 Sangho Na <microamp@protonmail.com>

;; Author: Sangho Na
;; Version: 0.1
;; Package-Requires: ((emacs "24"))

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:

;;; Code:

(deftheme shinmunji)

;; TODO
(let ((class '((class color) (min-colors 89)))
      (shinmunji-main-bg "#feffea")
      (shinmunji-main-fg "#130f06")
      (shinmunji-gray-1 "#6c6c6c")
      (shinmunji-gray-2 "#7c6b54")
      (shinmunji-gray-3 "#ede6d4")
      (shinmunji-yellow-1 "#ffd700")
      (shinmunji-green-1 "#9acd32")
      (shinmunji-blue-1 "#5d7f8c")
      (shinmunji-magenta-1 "#db7093")
      (shinmunji-red-1 "#ee4233")
      (shinmunji-orange-1 "#d78700"))
  (custom-theme-set-faces
   'shinmunji
   `(ac-completion-face ((,class (:underline t :foreground ,shinmunji-main-fg))))
   `(anzu-mode-line ((,class (:box t :background ,shinmunji-main-bg :foreground ,shinmunji-main-fg))))
   `(avy-lead-face ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg :bold t))))
   `(avy-lead-face-0 ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg :bold t))))
   `(avy-lead-face-1 ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg :bold t))))
   `(avy-lead-face-2 ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg :bold t))))
   `(aw-leading-char-face ((,class (:foreground ,shinmunji-red-1 :height 2.5))))
   `(bm-face ((,class (:background ,shinmunji-orange-1 :foreground ,shinmunji-main-bg))))
   `(cargo-process--errno-face ((,class (:foreground ,shinmunji-blue-1))))
   `(cargo-process--ok-face ((,class (:foreground ,shinmunji-green-1))))
   `(cargo-process--standard-face ((,class (:background ,shinmunji-main-bg :foreground ,shinmunji-gray-1))))
   `(cider-fringe-good-face ((,class (:foreground ,shinmunji-green-1))))
   `(compilation-error ((,class (:foreground ,shinmunji-red-1))))
   `(cursor ((,class (:foreground ,shinmunji-main-bg :background ,shinmunji-gray-2))))
   `(default ((,class (:background ,shinmunji-main-bg :foreground ,shinmunji-main-fg))))
   `(default-italic ((,class (:italic t))))
   `(eyebrowse-mode-line-active ((,class (:bold t :underline (:color ,shinmunji-red-1)))))
   `(dired-directory ((,class (:bold t))))
   `(ffap ((,class (:foreground ,shinmunji-main-fg))))
   `(font-latex-bold-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-latex-italic-face ((,class (:foreground ,shinmunji-main-fg :italic t))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,shinmunji-main-fg))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,shinmunji-main-fg))))
   `(font-latex-string-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-builtin-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-comment-face ((,class (:foreground ,shinmunji-gray-1))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-constant-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-doc-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-function-name-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-keyword-face ((,class (:foreground ,shinmunji-main-fg :bold t))))
   `(font-lock-negation-char-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-reference-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-string-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-type-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-variable-name-face ((,class (:foreground ,shinmunji-main-fg))))
   `(font-lock-warning-face ((,class (:foreground ,shinmunji-red-1))))
   `(fringe ((,class (:background ,shinmunji-main-bg :foreground ,shinmunji-main-fg))))
   `(git-gutter+-added ((,class (:foreground ,shinmunji-main-bg))))
   `(git-gutter+-deleted ((,class (:foreground ,shinmunji-main-bg))))
   `(git-gutter+-modified ((,class (:foreground ,shinmunji-main-bg))))
   `(git-gutter:added ((,class (:foreground ,shinmunji-gray-1))))
   `(git-gutter:deleted ((,class (:foreground ,shinmunji-gray-1 :bold t))))
   `(git-gutter:modified ((,class (:foreground ,shinmunji-gray-1))))
   `(gnus-header-content ((,class (:foreground ,shinmunji-main-fg))))
   `(gnus-header-from ((,class (:foreground ,shinmunji-main-fg))))
   `(gnus-header-name ((,class (:foreground ,shinmunji-main-fg))))
   `(gnus-header-subject ((,class (:foreground ,shinmunji-main-fg :bold t))))
   `(highlight ((,class (:foreground ,shinmunji-main-bg :background ,shinmunji-gray-1))))
   `(highlight-thing ((,class (:background ,shinmunji-gray-3))))
   `(hi-black-b ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg))))
   `(hi-black-hb ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-fg))))
   `(hi-blue-b ((,class (:background "blue3" :foreground ,shinmunji-main-bg))))
   `(hi-green-b ((,class (:background "green3" :foreground ,shinmunji-main-fg))))
   `(hi-red-b ((,class (:background "red3" :foreground ,shinmunji-main-bg))))
   `(hi-yellow ((,class (:background "yellow3" :foreground ,shinmunji-main-fg))))
   `(hl-line ((,class (:background "gainsboro"))))
   `(icompletep-determined ((,class :foreground ,shinmunji-main-fg)))
   `(ido-first-match ((,class (:foreground ,shinmunji-main-fg :bold t))))
   `(ido-only-match ((,class (:foreground ,shinmunji-red-1))))
   `(info-quoted-name ((,class (:foreground ,shinmunji-main-fg))))
   `(info-string ((,class (:foreground ,shinmunji-main-fg))))
   `(isearch ((,class (:inherit :highlight))))
   `(js2-external-variable ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-function-param ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-jsdoc-value ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-private-function-call ((,class (:foreground ,shinmunji-main-fg))))
   `(js2-private-member ((,class (:foreground ,shinmunji-main-fg))))
   `(lazy-highlight ((,class (:background ,shinmunji-gray-2 :foreground ,shinmunji-main-bg))))
   `(link ((,class (:foreground ,shinmunji-main-fg :underline t))))
   `(magit-branch ((,class (:foreground ,shinmunji-main-fg :weight bold))))
   `(magit-diff-context-highlight ((,class (:background ,shinmunji-main-bg))))
   `(magit-diff-file-header ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(magit-diffstat-added ((,class (:foreground ,shinmunji-main-fg))))
   `(magit-diffstat-removed ((,class (:foreground ,shinmunji-main-fg))))
   `(magit-hash ((,class (:foreground ,shinmunji-main-fg))))
   `(magit-hunk-heading ((,class (:background ,shinmunji-main-fg))))
   `(magit-hunk-heading-highlight ((,class (:background ,shinmunji-main-fg))))
   `(magit-item-highlight ((,class :background ,shinmunji-main-fg)))
   `(magit-log-author ((,class (:foreground ,shinmunji-main-fg))))
   `(magit-popup-option-value ((,class (:foreground ,shinmunji-orange-1))))
   `(magit-process-ng ((,class (:foreground ,shinmunji-red-1 :weight bold))))
   `(magit-process-ok ((,class (:foreground ,shinmunji-main-fg :weight bold))))
   `(magit-section-heading ((,class (:foreground ,shinmunji-main-fg :weight bold))))
   `(magit-section-highlight ((,class (:background nil))))
   `(message-header-name ((,class (:foreground ,shinmunji-main-fg))))
   `(minibuffer-prompt ((,class (:foreground ,shinmunji-main-fg))))
   `(mode-line ((,class (:line-width 1 :foreground ,shinmunji-main-fg :background ,shinmunji-main-bg :box t))))
   `(mode-line-inactive ((,class (:line-width 1 :foreground ,shinmunji-gray-3 :background ,shinmunji-main-bg :box t))))
   `(mu4e-cited-1-face ((,class (:foreground ,shinmunji-main-fg))))
   `(mu4e-cited-7-face ((,class (:foreground ,shinmunji-main-fg))))
   `(mu4e-header-highlight-face ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(mu4e-header-marks-face ((,class (:foreground ,shinmunji-main-fg))))
   `(mu4e-highlight-face ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-bg))))
   `(mu4e-view-url-number-face ((,class (:foreground ,shinmunji-main-fg))))
   `(org-agenda-clocking ((,class (:background ,shinmunji-yellow-1 :bold t))))
   `(org-agenda-date ((,class (:foreground ,shinmunji-main-fg :height 1.0))))
   `(org-agenda-date-today ((,class (:weight bold :foreground ,shinmunji-main-fg :height 1.0))))
   `(org-agenda-date-weekend ((,class (:weight normal :foreground ,shinmunji-main-fg))))
   `(org-agenda-done ((,class (:foreground ,shinmunji-main-fg))))
   `(org-agenda-structure ((,class (:weight bold :foreground ,shinmunji-main-fg :color ,shinmunji-main-fg :background ,shinmunji-main-bg :underline t))))
   `(org-block ((,class (:foreground ,shinmunji-main-fg))))
   `(org-code ((,class (:foreground ,shinmunji-main-fg))))
   `(org-date ((,class (:underline t :foreground ,shinmunji-main-fg))))
   `(org-date-selected ((,class (:background ,shinmunji-main-fg :foreground ,shinmunji-main-bg))))
   `(org-document-info-keyword ((,class (:foreground ,shinmunji-main-fg))))
   `(org-done ((,class (:line-width 1 :background ,shinmunji-main-bg :foreground "red" :bold t :underline t))))
   `(org-ellipsis ((,class (:foreground ,shinmunji-main-fg))))
   `(org-footnote  ((,class (:underline t :foreground ,shinmunji-main-fg))))
   `(org-headline-done ((,class (:background ,shinmunji-main-bg :foreground ,shinmunji-main-fg))))
   `(org-hide ((,class (:foreground ,shinmunji-main-fg))))
   `(org-level-1 ((,class (:foreground ,shinmunji-main-fg :height 1.0 :bold nil))))
   `(org-level-2 ((,class (:bold nil :foreground ,shinmunji-main-fg))))
   `(org-level-3 ((,class (:foreground ,shinmunji-main-fg))))
   `(org-level-4 ((,class (:bold nil :foreground ,shinmunji-main-fg))))
   `(org-level-4 ((,class (:bold nil :foreground ,shinmunji-main-fg))))
   `(org-link ((,class (:underline t :foreground ,shinmunji-main-fg))))
   `(org-mode-line-clock ((,class (:inherit nil))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-scheduled ((,class (:foreground ,shinmunji-main-fg))))
   `(org-scheduled-today ((,class (:foreground ,shinmunji-main-fg :weight bold :height 1.0))))
   `(org-sexp-date ((,class (:foreground ,shinmunji-main-fg))))
   `(org-special-keyword ((,class (:foreground ,shinmunji-main-fg))))
   `(org-table ((,class (:foreground ,shinmunji-main-fg))))
   `(org-todo ((,class (:line-width 1 :color ,shinmunji-main-fg :foreground ,shinmunji-main-fg :bold t))))
   `(org-verbatim ((,class (:foreground ,shinmunji-main-fg))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-warning ((,class (:underline t :foreground ,shinmunji-red-1))))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,shinmunji-main-fg)))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,shinmunji-red-1)))
   `(region ((,class (:background ,shinmunji-gray-2 :foreground ,shinmunji-main-bg))))
   `(secondary-selection ((,class :background ,shinmunji-gray-3)))
   `(sh-quoted-exec ((,class (:background nil :foreground ,shinmunji-red-1))))
   `(term ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-bg))))
   `(term-color-black ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-blue ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-cyan ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-green ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-magenta ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-red ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-white ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(term-color-yellow ((,class (:foreground ,shinmunji-main-fg :background ,shinmunji-main-fg))))
   `(trailing-whitespace ((,class :foreground nil :background ,shinmunji-red-1)))
   `(undo-tree-visualizer-current-face ((,class :foreground ,shinmunji-main-fg)))
   `(undo-tree-visualizer-default-face ((,class :foreground ,shinmunji-main-fg)))
   `(undo-tree-visualizer-register-face ((,class :foreground ,shinmunji-main-fg)))
   `(undo-tree-visualizer-unmodified-face ((,class :foreground ,shinmunji-main-fg)))
   `(vertical-border ((,class (:foreground ,shinmunji-main-fg))))
   `(warning ((,class (:foreground ,shinmunji-red-1))))
   `(web-mode-builtin-face ((,class (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face ((,class (:inherit ,font-lock-constant-face))))
   `(web-mode-doctype-face ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-function-name-face ((,class (:inherit ,font-lock-function-name-face))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,shinmunji-main-fg))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,shinmunji-main-fg))))
   `(web-mode-html-tag-face ((,class (:foreground ,shinmunji-main-fg))))
   `(web-mode-keyword-face ((,class (:foreground ,shinmunji-main-fg))))
   `(web-mode-string-face ((,class (:foreground ,shinmunji-main-fg))))
   `(web-mode-type-face ((,class (:inherit ,font-lock-type-face))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'shinmunji)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; shinmunji-theme.el ends here
